
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: PRASHANTH S  ## put your name
title: 'Java Developer'  ## your title
location: New Jersey , NJ


## Social Profiles
facebook: http://github.com  ## your github account url




# Update all the sections by editing the files inside _includes folder.
